version: '3'

services:
  postgres:
    image: postgres:latest
    command: 'postgres -c config_file="/etc/postgresql/postgresql.conf"'
    environment:
      POSTGRES_PASSWORD: Passw0rd!
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init:/docker-entrypoint-initdb.d

# デフォルトログイン情報
# ユーザ: postgres
# データベース: postgres
